### ISSUE TITLE
Lack of description 

### ISSUE THREAD

**Issue by MAHOSSAN** [strongloop/loopback4-example-shopping#234]
Can you please add more details about adding controller, data migration, creating table into database. Most importantly I downloaded the project and tried to run it. I was getting errors npm cli not found. Module not found

**Comment by dhmlau** [comment]
@MAHOSSAN, thanks for pointing it out. 
I think the [Installation section ](https://github.com/strongloop/loopback4-example-shopping#installation) of the README should be updated since we've changed it to use monorepo.  To start, you'd need to start to run `npm start` for both packages `shopping` and `recommender`.  

For creating table, since we're using mongodb, so there's no need to create the table. As long as the database exists, it should be fine. 

With that, would you like to submit a PR to update the instructions? Thanks.

**Comment by MAHOSSAN** [comment]
I followed the instructions from installation section but I want to know where is html for rendering shopping cart page . How did you add the controller and service . For example when you add controller you have two options rest or empty . What was repositiory for adding controller?? 
I got the error when I run the project the node module not found .. what is solution of this error ..

**Comment by dhmlau** [comment]
It seems like the instruction in the `Installation` section is correct.  And you have a more descriptive issue https://github.com/strongloop/loopback4-example-shopping/issues/235.  So I'd like to continue the discussion over in #235 and closing this ticket. Thanks.
